import type { DhikrItem } from "./types";

/**
 * Curated adhkar. Every entry carries its source path. Where the author could
 * not personally confirm a grading, `reviewStatus` is "review" and the note
 * says why. No reference in this file is invented; when in doubt an item is
 * flagged, not embellished.
 */
export const ADHKAR: DhikrItem[] = [
  {
    id: "subhanallah",
    title: "SubhanAllah",
    arabic: "سُبْحَانَ ٱللَّهِ",
    transliteration: "SubhanAllah",
    translation: "Glory be to Allah — He is free of every imperfection.",
    source: {
      type: "hadith",
      collection: "Sahih Muslim",
      reference: "2698",
      grade: "sahih",
      note: "Saying SubhanAllah one hundred times is described as earning a thousand good deeds.",
    },
    occasions: ["general", "after-salah", "gratitude"],
    virtue:
      "The Prophet ﷺ asked whether any of us is unable to earn a thousand good deeds each day, and explained that saying SubhanAllah a hundred times does so. (Sahih Muslim 2698)",
    explanation:
      "Subhan comes from a root that carries the sense of moving swiftly away, of distance. To say SubhanAllah is to declare that Allah is far above every flaw, every limitation, every comparison. It is not praise for something He did; it is the recognition of what He is. When something in your life looks broken, this word reminds you that the One who governs it is not.",
    vocabulary: [
      { arabic: "سُبْحَانَ", transliteration: "subhana", meaning: "far removed from imperfection", note: "root s-b-ḥ: to glide, to move away swiftly" },
      { arabic: "ٱللَّهِ", transliteration: "Allahi", meaning: "of Allah" },
    ],
    concept: "tasbih",
    names: ["al-azim", "al-quddus"],
    reflectionPrompt: "What changes when you remember Allah's perfection while something in your life feels imperfect?",
    practicalApplication: "Say it when you notice beauty, and say it when you notice something you cannot fix. Both are moments to declare who Allah is.",
    defaultTarget: 33,
    secondsPerRepetition: 2,
    audio: "/audio/subhanallah.mp3",
    reviewStatus: "approved",
  },
  {
    id: "alhamdulillah",
    title: "Alhamdulillah",
    arabic: "ٱلْحَمْدُ لِلَّهِ",
    transliteration: "Alhamdulillah",
    translation: "All praise belongs to Allah.",
    source: { type: "hadith", collection: "Sahih Muslim", reference: "223", grade: "sahih" },
    occasions: ["gratitude", "general", "after-salah", "upon-waking"],
    virtue: "The Prophet ﷺ said that Alhamdulillah fills the scale. (Sahih Muslim 223)",
    explanation:
      "Hamd is praise offered with love and reverence, for what someone is and not only for what they give you. Shukr is thanks for a favour; hamd is wider than that. The definite article — al-hamd — means all praise, every kind of it, and li-llah means it belongs to Allah by right. Gratitude here is not a mood you wait for. It is a way of seeing.",
    vocabulary: [
      { arabic: "ٱلْحَمْدُ", transliteration: "al-hamdu", meaning: "all praise", note: "root ḥ-m-d: to praise with love and reverence" },
      { arabic: "لِلَّهِ", transliteration: "lillahi", meaning: "belongs to Allah" },
    ],
    concept: "hamd",
    names: ["al-hamid", "ash-shakur"],
    reflectionPrompt: "Name one blessing you received today without earning it.",
    practicalApplication: "Before you reach for your phone in the morning, let this be the first sentence of the day.",
    defaultTarget: 33,
    secondsPerRepetition: 2,
    audio: "/audio/alhamdulillah.mp3",
    reviewStatus: "approved",
  },
  {
    id: "allahu_akbar",
    title: "Allahu Akbar",
    arabic: "ٱللَّهُ أَكْبَرُ",
    transliteration: "Allahu Akbar",
    translation: "Allah is greater.",
    source: {
      type: "hadith",
      collection: "Sahih al-Bukhari",
      reference: "843",
      grade: "sahih",
      note: "SubhanAllah, Alhamdulillah and Allahu Akbar thirty-three times each after every prayer; see also Sahih Muslim 595.",
    },
    occasions: ["after-salah", "general", "difficulty"],
    virtue:
      "When the poorer Companions worried that the wealthy had surpassed them in good deeds, the Prophet ﷺ taught them to say SubhanAllah, Alhamdulillah and Allahu Akbar thirty-three times after every prayer. (Sahih al-Bukhari 843)",
    explanation:
      "Akbar is a comparative: greater. The sentence is deliberately unfinished. Greater than what? Than whatever is in front of you. Than the worry, the deadline, the person, the fear. The takbir does not deny the size of things; it puts them next to Allah, where they find their real proportion.",
    vocabulary: [
      { arabic: "ٱللَّهُ", transliteration: "Allahu", meaning: "Allah" },
      { arabic: "أَكْبَرُ", transliteration: "akbar", meaning: "greater", note: "root k-b-r: greatness; the form is comparative, not superlative" },
    ],
    concept: "takbir",
    names: ["al-azim", "al-kabir"],
    reflectionPrompt: "What worry becomes smaller when Allah is remembered as greater?",
    practicalApplication: "Say it quietly before something you are afraid of. Let it be the last thing you hear before you begin.",
    defaultTarget: 33,
    secondsPerRepetition: 2,
    audio: "/audio/allahu_akbar.mp3",
    reviewStatus: "approved",
  },
  {
    id: "la_ilaha_illallah",
    title: "La ilaha illallah",
    arabic: "لَا إِلَٰهَ إِلَّا ٱللَّهُ",
    transliteration: "La ilaha illallah",
    translation: "There is no god but Allah.",
    source: {
      type: "hadith",
      collection: "Jami' at-Tirmidhi",
      reference: "3383",
      grade: "hasan (Tirmidhi); graded sahih by al-Hakim",
      note: "The best dhikr is La ilaha illallah, and the best supplication is Alhamdulillah.",
    },
    occasions: ["general", "before-sleep", "after-salah"],
    virtue: "The Prophet ﷺ said the best remembrance is La ilaha illallah. (Jami' at-Tirmidhi 3383)",
    explanation:
      "The sentence has two movements. First a negation that clears the ground: la ilaha, no deity at all. Then an exception that fills it: illa Allah, except Allah. An ilah is anything worshipped, obeyed, loved or feared in the way only Allah deserves. The kalimah is not only a statement about the universe. It is a daily decision about what runs your heart.",
    vocabulary: [
      { arabic: "لَا", transliteration: "la", meaning: "no, there is not" },
      { arabic: "إِلَٰهَ", transliteration: "ilaha", meaning: "deity, object of worship", note: "root ʾ-l-h" },
      { arabic: "إِلَّا", transliteration: "illa", meaning: "except" },
      { arabic: "ٱللَّهُ", transliteration: "Allah", meaning: "Allah" },
    ],
    concept: "tawhid",
    names: ["al-ahad"],
    reflectionPrompt: "What would change if your heart had one true anchor today?",
    practicalApplication: "Notice one thing you feared or hoped for more than you should have. Say the kalimah with that thing in mind.",
    defaultTarget: 33,
    secondsPerRepetition: 3,
    audio: "/audio/la_ilaha_illallah.mp3",
    reviewStatus: "approved",
  },
  {
    id: "astaghfirullah",
    title: "Astaghfirullah",
    arabic: "أَسْتَغْفِرُ ٱللَّهَ",
    transliteration: "Astaghfirullah",
    translation: "I seek Allah's forgiveness.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6307", grade: "sahih" },
    occasions: ["forgiveness", "general", "after-salah", "evening"],
    virtue: "The Prophet ﷺ said: By Allah, I seek Allah's forgiveness and turn to Him in repentance more than seventy times a day. (Sahih al-Bukhari 6307)",
    explanation:
      "The root gh-f-r carries the sense of covering and protecting; a mighfar is a helmet. To seek maghfirah is to ask Allah to cover what you did and shield you from its harm. If the Prophet ﷺ, whose sins were forgiven, sought forgiveness more than seventy times a day, then istighfar is not only for the moment after a mistake. It is a way of standing before Allah honestly, every day.",
    vocabulary: [
      { arabic: "أَسْتَغْفِرُ", transliteration: "astaghfiru", meaning: "I seek forgiveness", note: "root gh-f-r: to cover, to protect" },
      { arabic: "ٱللَّهَ", transliteration: "Allaha", meaning: "Allah" },
    ],
    concept: "istighfar",
    names: ["al-ghafur", "at-tawwab"],
    reflectionPrompt: "What would it feel like to place this burden down before Allah?",
    practicalApplication: "Say it after an argument, after a wasted hour, after a sharp word. Not as punishment, as return.",
    defaultTarget: 33,
    secondsPerRepetition: 2,
    audio: "/audio/astaghfirullah.mp3",
    reviewStatus: "approved",
  },
  {
    id: "salawat",
    title: "Salawat",
    arabic: "ٱللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ",
    transliteration: "Allahumma salli 'ala Muhammad",
    translation: "O Allah, send blessings upon Muhammad.",
    source: { type: "hadith", collection: "Sahih Muslim", reference: "408", grade: "sahih" },
    occasions: ["general", "gratitude", "evening"],
    virtue: "Whoever sends one blessing upon me, Allah sends ten blessings upon him. (Sahih Muslim 408)",
    explanation:
      "Salah upon the Prophet ﷺ is a request that Allah honour him, praise him and raise his mention. It is one of the few acts of worship that Allah tells us He Himself performs (Qur'an 33:56). Every time you say it, you are joining something Allah and His angels are already doing. Love for the Prophet ﷺ becomes a sentence you can carry anywhere.",
    vocabulary: [
      { arabic: "ٱللَّهُمَّ", transliteration: "Allahumma", meaning: "O Allah" },
      { arabic: "صَلِّ", transliteration: "salli", meaning: "send blessings", note: "root ṣ-l-w; from Allah it means praise and honour" },
      { arabic: "عَلَىٰ", transliteration: "'ala", meaning: "upon" },
      { arabic: "مُحَمَّدٍ", transliteration: "Muhammad", meaning: "Muhammad ﷺ", note: "the one who is praised abundantly" },
    ],
    concept: "salawat",
    reflectionPrompt: "Let gratitude for the Prophet ﷺ soften one interaction today.",
    practicalApplication: "Say it whenever his name is mentioned, and more on Fridays.",
    defaultTarget: 33,
    secondsPerRepetition: 3,
    audio: "/audio/salawat.mp3",
    reviewStatus: "approved",
  },
  {
    id: "hawqala",
    title: "Hawqala",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِٱللَّهِ",
    transliteration: "La hawla wa la quwwata illa billah",
    translation: "There is no power to change and no strength except through Allah.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6409", grade: "sahih", note: "Also Sahih Muslim 2704." },
    occasions: ["difficulty", "general", "protection"],
    virtue: "The Prophet ﷺ called this phrase a treasure from the treasures of Paradise. (Sahih al-Bukhari 6409; Sahih Muslim 2704)",
    explanation:
      "Hawl is movement from one state to another; quwwah is the strength to hold a state. The phrase surrenders both: I cannot change anything, and I cannot sustain anything, except by Allah. It is said at the moment effort meets its limit. Strangely, it is not a phrase of giving up. It is what you say while you take the next step, knowing Who carries it.",
    vocabulary: [
      { arabic: "لَا", transliteration: "la", meaning: "no" },
      { arabic: "حَوْلَ", transliteration: "hawla", meaning: "power to change, movement", note: "root ḥ-w-l: to change, to shift" },
      { arabic: "وَلَا", transliteration: "wa la", meaning: "and no" },
      { arabic: "قُوَّةَ", transliteration: "quwwata", meaning: "strength" },
      { arabic: "إِلَّا", transliteration: "illa", meaning: "except" },
      { arabic: "بِٱللَّهِ", transliteration: "billah", meaning: "through Allah" },
    ],
    concept: "tawakkul",
    names: ["al-qadir", "al-wakil"],
    reflectionPrompt: "What can you release after doing the next right thing?",
    practicalApplication: "Say it when you feel stuck, and say it again when you finally move. Both moments belong to Allah.",
    defaultTarget: 33,
    secondsPerRepetition: 3,
    audio: "/audio/hawqala.mp3",
    reviewStatus: "approved",
  },
  {
    id: "quran_reading",
    title: "Qur'an recitation",
    arabic: "تِلَاوَةُ ٱلْقُرْآنِ",
    transliteration: "Tilawat al-Qur'an",
    translation: "Recitation of the Qur'an.",
    source: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "2910", grade: "hasan sahih (Tirmidhi)", note: "See also Sahih al-Bukhari 5027." },
    occasions: ["general", "morning", "evening"],
    virtue: "Whoever recites a letter from the Book of Allah receives a good deed, and a good deed is multiplied tenfold. (Jami' at-Tirmidhi 2910) The best of you are those who learn the Qur'an and teach it. (Sahih al-Bukhari 5027)",
    explanation:
      "Tilawah means to follow, to recite by following the words closely. The Qur'an is the dhikr Allah revealed: He calls it adh-Dhikr Himself (Qur'an 15:9). Reading even a few verses with attention is remembrance in its most direct form, because the words are His.",
    vocabulary: [
      { arabic: "تِلَاوَةُ", transliteration: "tilawatu", meaning: "recitation", note: "root t-l-w: to follow" },
      { arabic: "ٱلْقُرْآنِ", transliteration: "al-Qur'ani", meaning: "of the Qur'an", note: "root q-r-ʾ: to read, to recite" },
    ],
    concept: "tilawah",
    reflectionPrompt: "Take one meaning from the passage into the rest of your day.",
    practicalApplication: "Choose a few ayahs, read them slowly, then read their meaning. Let one line stay with you.",
    defaultTarget: 5,
    unit: "ayahs",
    secondsPerRepetition: 30,
    audio: "/audio/quran_reading.mp3",
    reviewStatus: "approved",
  },
  {
    id: "subhanallahi_wa_bihamdihi",
    title: "SubhanAllahi wa bihamdihi",
    arabic: "سُبْحَانَ ٱللَّهِ وَبِحَمْدِهِ",
    transliteration: "SubhanAllahi wa bihamdihi",
    translation: "Glory be to Allah, and with His praise.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6405", grade: "sahih", note: "Also Sahih Muslim 2691." },
    occasions: ["morning", "evening", "general"],
    virtue: "Whoever says SubhanAllahi wa bihamdihi a hundred times in a day has his sins wiped away, even if they were like the foam of the sea. (Sahih al-Bukhari 6405; Sahih Muslim 2691)",
    explanation:
      "This phrase joins the two great movements of dhikr. Tasbih removes from Allah everything that does not befit Him; hamd affirms for Him everything beautiful. The wa bihamdihi means: I glorify Him, and I do so while praising Him. Negation and affirmation together, like the two halves of the kalimah.",
    vocabulary: [
      { arabic: "سُبْحَانَ ٱللَّهِ", transliteration: "SubhanAllahi", meaning: "Glory be to Allah" },
      { arabic: "وَبِحَمْدِهِ", transliteration: "wa bihamdihi", meaning: "and with His praise", note: "bi-: with; ḥamd: praise; -hi: His" },
    ],
    concept: "tasbih",
    names: ["al-hamid"],
    reflectionPrompt: "Which is easier for you today: declaring what Allah is not, or praising what He is?",
    practicalApplication: "A hundred repetitions take about three minutes. It fits into a walk, a commute, or the minutes before sleep.",
    defaultTarget: 100,
    secondsPerRepetition: 2,
    reviewStatus: "approved",
  },
  {
    id: "subhanallahi_wa_bihamdihi_azim",
    title: "The two light words",
    arabic: "سُبْحَانَ ٱللَّهِ وَبِحَمْدِهِ، سُبْحَانَ ٱللَّهِ ٱلْعَظِيمِ",
    transliteration: "SubhanAllahi wa bihamdihi, SubhanAllahil-'Azim",
    translation: "Glory be to Allah and with His praise; glory be to Allah, the Magnificent.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6682", grade: "sahih", note: "Also Sahih Muslim 2694." },
    occasions: ["general", "gratitude"],
    virtue: "Two words that are light on the tongue, heavy on the scale, and beloved to the Most Merciful. (Sahih al-Bukhari 6682; Sahih Muslim 2694)",
    explanation:
      "Al-'Azim is the Magnificent, the One whose greatness has no edge. The hadith names three qualities of this phrase: light to say, heavy in worth, and beloved to Ar-Rahman. The gap between how small it feels and how much it weighs is the whole lesson of dhikr.",
    vocabulary: [
      { arabic: "ٱلْعَظِيمِ", transliteration: "al-'Azim", meaning: "the Magnificent", note: "root ʿ-ẓ-m: greatness in essence and rank" },
    ],
    concept: "tasbih",
    names: ["al-azim"],
    reflectionPrompt: "What else in your day is light to do and heavy in worth?",
    practicalApplication: "Pair it with something you already do daily, like locking the door or waiting for the kettle.",
    defaultTarget: 33,
    secondsPerRepetition: 4,
    reviewStatus: "approved",
  },
  {
    id: "tahlil_full",
    title: "The full tahlil",
    arabic: "لَا إِلَٰهَ إِلَّا ٱللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ ٱلْمُلْكُ وَلَهُ ٱلْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu, wa huwa 'ala kulli shay'in qadir",
    translation: "There is no god but Allah alone, without partner. His is the dominion and His is the praise, and He is able over all things.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "3293", grade: "sahih", note: "Also Sahih Muslim 2691." },
    occasions: ["morning", "evening", "after-salah", "protection"],
    virtue: "Whoever says it a hundred times in a day: it is for him like freeing ten slaves, a hundred good deeds are written for him, a hundred sins erased, and it is a protection from Shaytan that day until evening. (Sahih al-Bukhari 3293; Sahih Muslim 2691)",
    explanation:
      "This is the kalimah unfolded. Wahdahu: He alone. La sharika lah: nothing shares in His rule. Then two possessions: al-mulk, ownership of everything, and al-hamd, all praise. Then the closing: qadir, able over all things. Together they describe what it means for Allah to be the only ilah — He owns, He is praised, He can.",
    vocabulary: [
      { arabic: "وَحْدَهُ", transliteration: "wahdahu", meaning: "alone" },
      { arabic: "شَرِيكَ", transliteration: "sharik", meaning: "partner" },
      { arabic: "ٱلْمُلْكُ", transliteration: "al-mulk", meaning: "dominion, ownership" },
      { arabic: "قَدِيرٌ", transliteration: "qadir", meaning: "fully able", note: "root q-d-r: power, measure" },
    ],
    concept: "tawhid",
    names: ["al-qadir", "al-malik"],
    reflectionPrompt: "Whose approval did you seek today that only Allah can give?",
    practicalApplication: "Ten repetitions after Fajr and Maghrib; a hundred on a day you have time. Count with your fingers if you are away from the app.",
    defaultTarget: 33,
    secondsPerRepetition: 6,
    reviewStatus: "approved",
  },
  {
    id: "sayyid_al_istighfar",
    title: "Sayyid al-Istighfar",
    arabic:
      "ٱللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا ٱسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي، فَٱغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ ٱلذُّنُوبَ إِلَّا أَنْتَ",
    transliteration:
      "Allahumma anta Rabbi, la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bini'matika 'alayya, wa abu'u laka bidhanbi, faghfir li, fa innahu la yaghfirudh-dhunuba illa anta",
    translation:
      "O Allah, You are my Lord; there is no god but You. You created me and I am Your servant, and I keep Your covenant and promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge Your favour upon me, and I acknowledge my sin, so forgive me, for none forgives sins but You.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6306", grade: "sahih" },
    occasions: ["morning", "evening", "forgiveness"],
    virtue: "The Prophet ﷺ called this the master of seeking forgiveness, and said that whoever says it in the evening with certainty and dies that night enters Paradise, and likewise in the morning. (Sahih al-Bukhari 6306)",
    explanation:
      "The structure is the lesson. It begins with who Allah is, then who you are. It admits your effort is partial: as much as I am able. Then two acknowledgements side by side, abu'u laka: I own up to Your favour, I own up to my sin. Only after that comes the request. Honest istighfar holds gratitude and guilt in the same breath.",
    vocabulary: [
      { arabic: "رَبِّي", transliteration: "Rabbi", meaning: "my Lord", note: "rabb: the one who nurtures, owns and sustains" },
      { arabic: "عَبْدُكَ", transliteration: "'abduka", meaning: "Your servant" },
      { arabic: "عَهْدِكَ", transliteration: "'ahdika", meaning: "Your covenant" },
      { arabic: "أَبُوءُ", transliteration: "abu'u", meaning: "I acknowledge, I return with", note: "to come back carrying something" },
      { arabic: "نِعْمَتِكَ", transliteration: "ni'matika", meaning: "Your favour" },
      { arabic: "ذَنْبِي", transliteration: "dhanbi", meaning: "my sin" },
    ],
    concept: "istighfar",
    names: ["al-ghafur", "ar-rabb"],
    reflectionPrompt: "Which is harder to say honestly today: I acknowledge Your favour, or I acknowledge my sin?",
    practicalApplication: "Learn it in pieces. This week, say it once each morning and evening reading the meaning as you go.",
    defaultTarget: 1,
    secondsPerRepetition: 45,
    repetitionGuidance: "Once in the morning and once in the evening.",
    reviewStatus: "approved",
  },
  {
    id: "ayat_al_kursi",
    title: "Ayat al-Kursi",
    arabic:
      "ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ مَن ذَا ٱلَّذِى يَشْفَعُ عِندَهُۥٓ إِلَّا بِإِذْنِهِۦ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِۦٓ إِلَّا بِمَا شَآءَ ۚ وَسِعَ كُرْسِيُّهُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ ۖ وَلَا يَـُٔودُهُۥ حِفْظُهُمَا ۚ وَهُوَ ٱلْعَلِىُّ ٱلْعَظِيمُ",
    transliteration:
      "Allahu la ilaha illa huwal-Hayyul-Qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard, man dhal-ladhi yashfa'u 'indahu illa bi-idhnih, ya'lamu ma bayna aydihim wa ma khalfahum, wa la yuhituna bishay'im-min 'ilmihi illa bima sha', wasi'a kursiyyuhus-samawati wal-ard, wa la ya'uduhu hifzuhuma, wa huwal-'Aliyyul-'Azim",
    translation:
      "Allah — there is no god but He, the Ever-Living, the Sustainer of all. Neither drowsiness nor sleep overtakes Him. To Him belongs whatever is in the heavens and whatever is on the earth. Who can intercede with Him except by His permission? He knows what is before them and what is behind them, and they encompass nothing of His knowledge except what He wills. His Kursi extends over the heavens and the earth, and preserving them does not tire Him. He is the Most High, the Magnificent.",
    source: { type: "quran", collection: "Qur'an", reference: "2:255" },
    virtueSource: { type: "hadith", collection: "Sahih al-Bukhari", reference: "2311", grade: "sahih" },
    occasions: ["before-sleep", "protection", "morning", "evening", "after-salah"],
    virtue: "Whoever recites it when going to bed will have a guardian from Allah, and no devil will come near him until morning. (Sahih al-Bukhari 2311)",
    explanation:
      "The greatest ayah in the Qur'an is entirely about who Allah is. Al-Hayy: the Living, whose life has no beginning and no end. Al-Qayyum: the One who stands by Himself and by whom everything else stands. Neither slumber nor sleep — He never stops holding the world. When you recite it before sleep, you are handing yourself over to the One who does not.",
    vocabulary: [
      { arabic: "ٱلْحَىُّ", transliteration: "al-Hayy", meaning: "the Ever-Living" },
      { arabic: "ٱلْقَيُّومُ", transliteration: "al-Qayyum", meaning: "the Self-Sustaining, Sustainer of all", note: "root q-w-m: to stand, to establish" },
      { arabic: "سِنَةٌ", transliteration: "sinah", meaning: "drowsiness" },
      { arabic: "كُرْسِيُّهُ", transliteration: "kursiyyuhu", meaning: "His Kursi (footstool)" },
      { arabic: "ٱلْعَلِىُّ", transliteration: "al-'Aliyy", meaning: "the Most High" },
    ],
    concept: "tawhid",
    names: ["al-hayy", "al-qayyum", "al-azim"],
    reflectionPrompt: "What are you still carrying at night that Al-Qayyum is already holding?",
    practicalApplication: "Recite it once before sleep. If you do not know it by heart yet, read it from the screen and let the meaning sit with you.",
    defaultTarget: 1,
    secondsPerRepetition: 40,
    repetitionGuidance: "Once before sleep, and after each prayer.",
    reviewStatus: "approved",
  },
  {
    id: "hasbunallah",
    title: "Hasbunallah",
    arabic: "حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ",
    transliteration: "Hasbunallahu wa ni'mal-Wakil",
    translation: "Allah is sufficient for us, and He is the best Disposer of affairs.",
    source: { type: "quran", collection: "Qur'an", reference: "3:173" },
    virtueSource: { type: "hadith", collection: "Sahih al-Bukhari", reference: "4563", grade: "sahih" },
    occasions: ["difficulty", "protection", "general"],
    virtue: "Ibrahim said it when he was thrown into the fire, and Muhammad ﷺ said it when people warned him that an army had gathered against him. (Sahih al-Bukhari 4563)",
    explanation:
      "Hasb is sufficiency: enough. A wakil is the one you entrust your affairs to and who carries them through. The verse was said by people who had every reason to be afraid and chose reliance instead. It does not promise that the fire will not be lit. It says that Allah is enough, whatever is lit.",
    vocabulary: [
      { arabic: "حَسْبُنَا", transliteration: "hasbuna", meaning: "sufficient for us" },
      { arabic: "نِعْمَ", transliteration: "ni'ma", meaning: "how excellent is" },
      { arabic: "ٱلْوَكِيلُ", transliteration: "al-Wakil", meaning: "the Disposer of affairs, the Trustee", note: "root w-k-l: to entrust" },
    ],
    concept: "tawakkul",
    names: ["al-wakil"],
    reflectionPrompt: "What are you trying to be enough for that only Allah can be enough for?",
    practicalApplication: "Say it when you receive news you cannot control. Then do the next thing that is yours to do.",
    defaultTarget: 33,
    secondsPerRepetition: 3,
    reviewStatus: "approved",
  },
  {
    id: "dua_of_yunus",
    title: "The du'a of Yunus",
    arabic: "لَّآ إِلَٰهَ إِلَّآ أَنتَ سُبْحَٰنَكَ إِنِّى كُنتُ مِنَ ٱلظَّٰلِمِينَ",
    transliteration: "La ilaha illa anta, subhanaka, inni kuntu minaz-zalimin",
    translation: "There is no god but You. Glory be to You. Truly I have been among the wrongdoers.",
    source: { type: "quran", collection: "Qur'an", reference: "21:87" },
    virtueSource: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3505", grade: "hasan sahih (Tirmidhi); sahih (al-Hakim)" },
    occasions: ["difficulty", "forgiveness", "general"],
    virtue: "No Muslim calls upon Allah with these words concerning anything except that Allah answers him. (Jami' at-Tirmidhi 3505)",
    explanation:
      "Yunus said these words in the belly of the whale, in darkness upon darkness. Notice the order: tawhid first, then glorification, then confession. He does not begin with what he needs. He begins with Who Allah is, then admits his own wrong, and the request is not even spoken. Allah answered it anyway.",
    vocabulary: [
      { arabic: "سُبْحَٰنَكَ", transliteration: "subhanaka", meaning: "glory be to You" },
      { arabic: "إِنِّى", transliteration: "inni", meaning: "truly I" },
      { arabic: "ٱلظَّٰلِمِينَ", transliteration: "az-zalimin", meaning: "the wrongdoers", note: "root ẓ-l-m: to put something out of its place; darkness" },
    ],
    concept: "tawbah",
    names: ["al-ghafur"],
    reflectionPrompt: "What darkness are you in right now, and what would it mean to start with Allah's glory instead of your need?",
    practicalApplication: "When anxiety tightens, say it slowly and let the three parts land one at a time.",
    defaultTarget: 33,
    secondsPerRepetition: 4,
    reviewStatus: "approved",
  },
  {
    id: "dua_of_distress",
    title: "The du'a of distress",
    arabic:
      "لَا إِلَٰهَ إِلَّا ٱللَّهُ ٱلْعَظِيمُ ٱلْحَلِيمُ، لَا إِلَٰهَ إِلَّا ٱللَّهُ رَبُّ ٱلْعَرْشِ ٱلْعَظِيمِ، لَا إِلَٰهَ إِلَّا ٱللَّهُ رَبُّ ٱلسَّمَاوَاتِ وَرَبُّ ٱلْأَرْضِ وَرَبُّ ٱلْعَرْشِ ٱلْكَرِيمِ",
    transliteration:
      "La ilaha illallahul-'Azimul-Halim, la ilaha illallahu Rabbul-'Arshil-'Azim, la ilaha illallahu Rabbus-samawati wa Rabbul-ardi wa Rabbul-'Arshil-Karim",
    translation:
      "There is no god but Allah, the Magnificent, the Forbearing. There is no god but Allah, Lord of the Magnificent Throne. There is no god but Allah, Lord of the heavens and Lord of the earth and Lord of the Noble Throne.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6346", grade: "sahih", note: "Also Sahih Muslim 2730." },
    occasions: ["difficulty", "protection"],
    virtue: "The Prophet ﷺ used to say these words at times of distress. (Sahih al-Bukhari 6346; Sahih Muslim 2730)",
    explanation:
      "Three times the kalimah, each time with different Names. Al-Halim, the Forbearing, who does not rush to punish. Rabb al-'Arsh, Lord of the Throne, greater than anything that frightens you. The du'a of distress contains no request at all. It is the heart finding its footing by remembering who is in charge.",
    vocabulary: [
      { arabic: "ٱلْحَلِيمُ", transliteration: "al-Halim", meaning: "the Forbearing" },
      { arabic: "ٱلْعَرْشِ", transliteration: "al-'Arsh", meaning: "the Throne" },
      { arabic: "ٱلْكَرِيمِ", transliteration: "al-Karim", meaning: "the Noble, the Generous" },
    ],
    concept: "tawhid",
    names: ["al-azim", "al-halim", "al-karim"],
    reflectionPrompt: "In distress, do you reach first for a solution or for the One who holds the Throne?",
    practicalApplication: "Learn it in three lines. Each line is a full breath.",
    defaultTarget: 3,
    secondsPerRepetition: 20,
    reviewStatus: "approved",
  },
  {
    id: "istirja",
    title: "Istirja'",
    arabic: "إِنَّا لِلَّهِ وَإِنَّآ إِلَيْهِ رَٰجِعُونَ، ٱللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا",
    transliteration: "Inna lillahi wa inna ilayhi raji'un. Allahumma'jurni fi musibati wa akhlif li khayran minha",
    translation: "Truly we belong to Allah and to Him we return. O Allah, reward me in my affliction and replace it for me with something better.",
    source: { type: "quran", collection: "Qur'an", reference: "2:156" },
    virtueSource: { type: "hadith", collection: "Sahih Muslim", reference: "918", grade: "sahih" },
    occasions: ["difficulty"],
    virtue: "Whoever says these words at a loss, Allah rewards him in his affliction and gives him something better in its place. Umm Salamah said it when her husband died, and Allah gave her the Prophet ﷺ. (Sahih Muslim 918)",
    explanation:
      "The Qur'anic sentence changes the meaning of loss. Nothing was ever yours; it belonged to Allah and has returned to Him, as you will. The Prophet ﷺ added a request: reward me for this, and replace it with better. Grief is allowed. Despair is not, because the story is not over.",
    vocabulary: [
      { arabic: "رَٰجِعُونَ", transliteration: "raji'un", meaning: "those who return" },
      { arabic: "مُصِيبَتِي", transliteration: "musibati", meaning: "my affliction" },
      { arabic: "أَخْلِفْ", transliteration: "akhlif", meaning: "replace, give in place of" },
    ],
    concept: "sabr",
    reflectionPrompt: "What loss are you still holding as if it had been yours to keep?",
    practicalApplication: "Say it for small losses too: a missed train, a broken thing. The habit is ready when the large loss comes.",
    defaultTarget: 7,
    secondsPerRepetition: 8,
    reviewStatus: "approved",
  },
  {
    id: "radeetu",
    title: "Raditu billahi Rabba",
    arabic: "رَضِيتُ بِٱللَّهِ رَبًّا، وَبِٱلْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ رَسُولًا",
    transliteration: "Raditu billahi Rabban, wa bil-Islami dinan, wa bi-Muhammadin rasula",
    translation: "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as Messenger.",
    source: { type: "hadith", collection: "Sahih Muslim", reference: "1884", grade: "sahih", note: "Paradise is due to whoever says these words." },
    occasions: ["morning", "evening"],
    virtue: "Whoever says: I am pleased with Allah as Lord, Islam as religion and Muhammad as Messenger, Paradise is due to him. (Sahih Muslim 1884) A narration in Abu Dawud 5072 describes saying it three times morning and evening; scholars differ on the grading of that narration.",
    explanation:
      "Rida is contentment that goes deeper than acceptance. To say it about Allah as Rabb is to be at peace with how He runs your life, including the parts you did not choose. Said in the morning, it sets the terms of the day before the day sets them for you.",
    vocabulary: [
      { arabic: "رَضِيتُ", transliteration: "raditu", meaning: "I am pleased, content", note: "root r-ḍ-y: contentment" },
      { arabic: "رَبًّا", transliteration: "Rabban", meaning: "as Lord" },
      { arabic: "دِينًا", transliteration: "dinan", meaning: "as religion, way of life" },
    ],
    concept: "rida",
    names: ["ar-rabb"],
    reflectionPrompt: "Which decree of Allah in your life are you still negotiating with?",
    practicalApplication: "Say it three times after waking, before the first message of the day.",
    defaultTarget: 3,
    secondsPerRepetition: 8,
    reviewStatus: "review",
  },
  {
    id: "bismillah_protection",
    title: "Bismillahil-ladhi",
    arabic: "بِسْمِ ٱللَّهِ ٱلَّذِي لَا يَضُرُّ مَعَ ٱسْمِهِ شَيْءٌ فِي ٱلْأَرْضِ وَلَا فِي ٱلسَّمَاءِ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ",
    transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama', wa huwas-Sami'ul-'Alim",
    translation: "In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, the All-Knowing.",
    source: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3388", grade: "hasan sahih (Tirmidhi)", note: "Also Sunan Abi Dawud 5088." },
    occasions: ["morning", "evening", "protection"],
    virtue: "Whoever says it three times in the morning and three times in the evening, nothing will harm him. (Jami' at-Tirmidhi 3388; Sunan Abi Dawud 5088)",
    explanation:
      "Protection in Islam is not a charm. It is a Name. The phrase does not say that nothing bad will happen; it says that with His Name, harm loses its grip. It ends with two Names that answer the two fears of the anxious heart: that no one hears, and that no one knows. He hears. He knows.",
    vocabulary: [
      { arabic: "يَضُرُّ", transliteration: "yadurru", meaning: "harms" },
      { arabic: "ٱلسَّمِيعُ", transliteration: "as-Sami'", meaning: "the All-Hearing" },
      { arabic: "ٱلْعَلِيمُ", transliteration: "al-'Alim", meaning: "the All-Knowing" },
    ],
    concept: "protection",
    names: ["as-sami", "al-alim"],
    reflectionPrompt: "What do you protect yourself with that is not Allah's Name?",
    practicalApplication: "Three times after Fajr, three times after Maghrib. It takes under a minute.",
    defaultTarget: 3,
    secondsPerRepetition: 10,
    reviewStatus: "approved",
  },
  {
    id: "audhu_bikalimat",
    title: "A'udhu bikalimatillah",
    arabic: "أَعُوذُ بِكَلِمَاتِ ٱللَّهِ ٱلتَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    source: { type: "hadith", collection: "Sahih Muslim", reference: "2708", grade: "sahih" },
    occasions: ["protection", "evening", "travel"],
    virtue: "Whoever stops at a place and says these words, nothing will harm him until he leaves that place. (Sahih Muslim 2708)",
    explanation:
      "Allah's words are tammah, perfect and complete: nothing is missing from them and nothing false enters them. To seek refuge in them is to step inside something whole. The phrase names creation as the source of harm, not the Creator. Everything that can hurt you is created, and its Creator is where you hide.",
    vocabulary: [
      { arabic: "أَعُوذُ", transliteration: "a'udhu", meaning: "I seek refuge", note: "root ʿ-w-dh: to take shelter" },
      { arabic: "كَلِمَاتِ", transliteration: "kalimat", meaning: "words" },
      { arabic: "ٱلتَّامَّاتِ", transliteration: "at-tammat", meaning: "the perfect, complete" },
    ],
    concept: "protection",
    reflectionPrompt: "Where do you go when you are afraid, and is it whole?",
    practicalApplication: "Say it when you arrive somewhere new, and in the evening.",
    defaultTarget: 3,
    secondsPerRepetition: 6,
    reviewStatus: "approved",
  },
  {
    id: "sleep_bismika",
    title: "Before sleep",
    arabic: "بِٱسْمِكَ ٱللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya",
    translation: "In Your name, O Allah, I die and I live.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6324", grade: "sahih" },
    occasions: ["before-sleep"],
    virtue: "The Prophet ﷺ said it when he went to bed. (Sahih al-Bukhari 6324)",
    explanation:
      "Sleep is called a small death in the Qur'an (39:42). This sentence names it honestly: I die and I live, and both are in Your name. The day is over; you did not finish everything; you hand it back. The one who says it sleeps as a servant, not as a manager.",
    vocabulary: [
      { arabic: "بِٱسْمِكَ", transliteration: "bismika", meaning: "in Your name" },
      { arabic: "أَمُوتُ", transliteration: "amutu", meaning: "I die" },
      { arabic: "أَحْيَا", transliteration: "ahya", meaning: "I live" },
    ],
    concept: "tawakkul",
    reflectionPrompt: "What would you have to release to sleep as a servant tonight?",
    practicalApplication: "Make it the last sentence before the screen goes dark.",
    defaultTarget: 1,
    secondsPerRepetition: 5,
    reviewStatus: "approved",
  },
  {
    id: "waking_alhamdulillah",
    title: "Upon waking",
    arabic: "ٱلْحَمْدُ لِلَّهِ ٱلَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ ٱلنُّشُورُ",
    transliteration: "Alhamdulillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    translation: "All praise is for Allah who gave us life after He caused us to die, and to Him is the resurrection.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6312", grade: "sahih" },
    occasions: ["upon-waking", "morning", "gratitude"],
    virtue: "The Prophet ﷺ said it when he woke. (Sahih al-Bukhari 6312)",
    explanation:
      "The first sentence of the day is praise, and the reason for praise is that you woke up. Nushur is the resurrection; every morning rehearses it. Before you have checked anything or answered anyone, the day already has a direction: from Allah, back to Allah.",
    vocabulary: [
      { arabic: "أَحْيَانَا", transliteration: "ahyana", meaning: "gave us life" },
      { arabic: "أَمَاتَنَا", transliteration: "amatana", meaning: "caused us to die" },
      { arabic: "ٱلنُّشُورُ", transliteration: "an-nushur", meaning: "the resurrection, the rising" },
    ],
    concept: "hamd",
    reflectionPrompt: "If waking is a small resurrection, what will you do with the day you were given back?",
    practicalApplication: "Leave your phone across the room. Say this before you reach for it.",
    defaultTarget: 1,
    secondsPerRepetition: 6,
    reviewStatus: "approved",
  },
  {
    id: "leaving_home",
    title: "Leaving home",
    arabic: "بِسْمِ ٱللَّهِ، تَوَكَّلْتُ عَلَى ٱللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِٱللَّهِ",
    transliteration: "Bismillah, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
    translation: "In the name of Allah, I place my trust in Allah, and there is no power to change nor strength except through Allah.",
    source: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3426", grade: "hasan sahih gharib (Tirmidhi)", note: "Also Sunan Abi Dawud 5095." },
    occasions: ["home", "morning", "protection", "travel"],
    virtue: "Whoever says it when leaving his house is told: you are guided, sufficed and protected, and Shaytan withdraws from him. (Jami' at-Tirmidhi 3426)",
    explanation:
      "Three movements at the threshold. Bismillah: I begin with Him. Tawakkaltu: I have entrusted the outcome to Him. Hawqala: I admit I cannot do this alone. The door is a small moment; the sentence makes it a decision about how you will walk through the world today.",
    vocabulary: [
      { arabic: "تَوَكَّلْتُ", transliteration: "tawakkaltu", meaning: "I have placed my trust", note: "root w-k-l" },
    ],
    concept: "tawakkul",
    names: ["al-wakil"],
    reflectionPrompt: "What are you walking out to meet today, and Who is walking with you?",
    practicalApplication: "Pair it with the door handle. In a week it will say itself.",
    defaultTarget: 7,
    secondsPerRepetition: 6,
    reviewStatus: "approved",
  },
  {
    id: "bismillah_eating",
    title: "Bismillah when eating",
    arabic: "بِسْمِ ٱللَّهِ",
    transliteration: "Bismillah",
    translation: "In the name of Allah.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "5376", grade: "sahih", note: "Also Sahih Muslim 2022. If forgotten at the start: Bismillahi awwalahu wa akhirahu (Sunan Abi Dawud 3767; Jami' at-Tirmidhi 1858)." },
    occasions: ["eating", "home", "general"],
    virtue: "The Prophet ﷺ told a boy: Mention the name of Allah, eat with your right hand, and eat from what is nearest to you. (Sahih al-Bukhari 5376; Sahih Muslim 2022)",
    explanation:
      "The shortest dhikr in the language, and one of the most frequent. To begin with Allah's name is to admit that the food, the hands, the appetite and the moment are all His. If you forget and remember mid-meal, the Sunnah is to say: Bismillahi awwalahu wa akhirahu — in Allah's name, at its beginning and its end.",
    vocabulary: [
      { arabic: "بِسْمِ", transliteration: "bismi", meaning: "in the name of" },
      { arabic: "ٱللَّهِ", transliteration: "Allah", meaning: "Allah" },
    ],
    concept: "barakah",
    reflectionPrompt: "How many times today did you begin something without Him?",
    practicalApplication: "Every meal, every drink. A day has more beginnings than you think.",
    defaultTarget: 7,
    secondsPerRepetition: 2,
    reviewStatus: "approved",
  },
  {
    id: "after_eating",
    title: "After eating",
    arabic: "ٱلْحَمْدُ لِلَّهِ ٱلَّذِي أَطْعَمَنِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration: "Alhamdulillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation: "All praise is for Allah who fed me this and provided it for me without any power or strength on my part.",
    source: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3458", grade: "hasan gharib (Tirmidhi)", note: "Also Sunan Abi Dawud 4023. Grading should be confirmed by a reviewer." },
    occasions: ["eating", "gratitude", "provision"],
    virtue: "Whoever says it after eating, his past sins are forgiven. (Jami' at-Tirmidhi 3458; Sunan Abi Dawud 4023)",
    explanation:
      "The sentence separates two things we usually confuse: the meal and the provision behind it. Razaqa is provision; rizq reaches you through a chain of causes you did not build. The ending is the hawqala turned inward: none of this came from my strength.",
    vocabulary: [
      { arabic: "أَطْعَمَنِي", transliteration: "at'amani", meaning: "fed me" },
      { arabic: "رَزَقَنِيهِ", transliteration: "razaqanihi", meaning: "provided it for me", note: "root r-z-q: provision" },
    ],
    concept: "rizq",
    names: ["ar-razzaq"],
    reflectionPrompt: "Trace one meal back through the hands that brought it to you. Where does the chain end?",
    practicalApplication: "Say it before you stand up from the table.",
    defaultTarget: 3,
    secondsPerRepetition: 8,
    reviewStatus: "review",
  },
  {
    id: "after_salah_salam",
    title: "After salah",
    arabic: "أَسْتَغْفِرُ ٱللَّهَ (ثَلَاثًا)، ٱللَّهُمَّ أَنْتَ ٱلسَّلَامُ وَمِنْكَ ٱلسَّلَامُ، تَبَارَكْتَ يَا ذَا ٱلْجَلَالِ وَٱلْإِكْرَامِ",
    transliteration: "Astaghfirullah (three times). Allahumma antas-Salam wa minkas-salam, tabarakta ya Dhal-Jalali wal-Ikram",
    translation: "I seek Allah's forgiveness (three times). O Allah, You are Peace and from You is peace. Blessed are You, O Possessor of Majesty and Honour.",
    source: { type: "hadith", collection: "Sahih Muslim", reference: "591", grade: "sahih" },
    occasions: ["after-salah"],
    virtue: "When the Prophet ﷺ finished his prayer he would seek forgiveness three times and then say these words. (Sahih Muslim 591)",
    explanation:
      "The very first thing after prayer is istighfar, for the prayer itself: for the wandering mind, the hurried ruku'. Then the Name As-Salam, the One who is Peace and the source of every peace. You leave the prayer not congratulating yourself but asking to be covered, and then naming where peace actually comes from.",
    vocabulary: [
      { arabic: "ٱلسَّلَامُ", transliteration: "as-Salam", meaning: "Peace, the Source of Peace" },
      { arabic: "تَبَارَكْتَ", transliteration: "tabarakta", meaning: "blessed are You" },
      { arabic: "ٱلْجَلَالِ", transliteration: "al-jalal", meaning: "majesty" },
      { arabic: "ٱلْإِكْرَامِ", transliteration: "al-ikram", meaning: "honour, generosity" },
    ],
    concept: "salah",
    names: ["as-salam"],
    reflectionPrompt: "What would change if you asked forgiveness for your worship, not only for your sins?",
    practicalApplication: "Stay seated for thirty seconds after the taslim. This is the first thing to say.",
    defaultTarget: 1,
    secondsPerRepetition: 15,
    repetitionGuidance: "After each of the five prayers.",
    reviewStatus: "approved",
  },
  {
    id: "after_salah_help",
    title: "Help me remember You",
    arabic: "ٱللَّهُمَّ أَعِنِّي عَلَىٰ ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    translation: "O Allah, help me to remember You, to thank You, and to worship You well.",
    source: { type: "hadith", collection: "Sunan Abi Dawud", reference: "1522", grade: "sahih (Ibn Hibban, al-Albani)", note: "Also Sunan an-Nasa'i 1303." },
    occasions: ["after-salah", "gratitude", "general"],
    virtue: "The Prophet ﷺ took Mu'adh by the hand and said: By Allah, I love you. Do not leave off saying after every prayer: O Allah, help me to remember You, thank You and worship You well. (Sunan Abi Dawud 1522)",
    explanation:
      "This is the du'a of this whole app. It admits that even remembrance needs help; you cannot do dhikr by willpower alone. Three requests in ascending order: to remember, to be grateful, and to worship well — husn, beauty in worship, not just quantity. It was given with love, hand in hand.",
    vocabulary: [
      { arabic: "أَعِنِّي", transliteration: "a'inni", meaning: "help me", note: "root ʿ-w-n: aid" },
      { arabic: "ذِكْرِكَ", transliteration: "dhikrika", meaning: "remembering You" },
      { arabic: "شُكْرِكَ", transliteration: "shukrika", meaning: "thanking You" },
      { arabic: "حُسْنِ", transliteration: "husn", meaning: "beauty, excellence" },
    ],
    concept: "dhikr",
    reflectionPrompt: "Which of the three do you need most help with this week: remembering, thanking, or worshipping well?",
    practicalApplication: "Say it after every prayer, the way Mu'adh was asked to.",
    defaultTarget: 3,
    secondsPerRepetition: 6,
    reviewStatus: "approved",
  },
  {
    id: "travel",
    title: "When travelling",
    arabic: "سُبْحَٰنَ ٱلَّذِى سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُۥ مُقْرِنِينَ وَإِنَّآ إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ",
    transliteration: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila Rabbina lamunqalibun",
    translation: "Glory be to Him who has subjected this to us, for we could never have done it ourselves. And truly to our Lord we will return.",
    source: { type: "quran", collection: "Qur'an", reference: "43:13–14" },
    virtueSource: { type: "hadith", collection: "Sahih Muslim", reference: "1342", grade: "sahih" },
    occasions: ["travel"],
    virtue: "The Prophet ﷺ said these words when he mounted his riding animal to travel. (Sahih Muslim 1342)",
    explanation:
      "Sakhkhara: He made it serve you. The car, the plane, the road: none of it was ever in your control. The verse ends with the journey behind every journey. Every departure rehearses the last one.",
    vocabulary: [
      { arabic: "سَخَّرَ", transliteration: "sakhkhara", meaning: "subjected, made to serve" },
      { arabic: "مُقْرِنِينَ", transliteration: "muqrinin", meaning: "able to control it" },
      { arabic: "لَمُنقَلِبُونَ", transliteration: "lamunqalibun", meaning: "surely returning" },
    ],
    concept: "tawhid",
    reflectionPrompt: "What in your daily movement do you take as yours that has only been subjected to you?",
    practicalApplication: "Say it when the engine starts, before the music does.",
    defaultTarget: 1,
    secondsPerRepetition: 12,
    reviewStatus: "approved",
  },
  {
    id: "family_dua",
    title: "For the family",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَٰجِنَا وَذُرِّيَّٰتِنَا قُرَّةَ أَعْيُنٍ وَٱجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
    translation: "Our Lord, grant us from our spouses and our offspring the coolness of our eyes, and make us an example for the God-conscious.",
    source: { type: "quran", collection: "Qur'an", reference: "25:74" },
    occasions: ["family", "general"],
    explanation:
      "This is the du'a of the servants of Ar-Rahman, listed among their qualities in Surah al-Furqan. Qurrat a'yun, coolness of the eyes, is the Arabic image for deep joy: eyes that rest because they see what they love doing well. The du'a does not ask for an easy family. It asks for one that helps you toward Allah, and for you to lead the way.",
    vocabulary: [
      { arabic: "هَبْ", transliteration: "hab", meaning: "grant, gift" },
      { arabic: "أَزْوَٰجِنَا", transliteration: "azwajina", meaning: "our spouses" },
      { arabic: "ذُرِّيَّٰتِنَا", transliteration: "dhurriyyatina", meaning: "our offspring" },
      { arabic: "قُرَّةَ أَعْيُنٍ", transliteration: "qurrata a'yun", meaning: "coolness of eyes, deep joy" },
      { arabic: "إِمَامًا", transliteration: "imama", meaning: "a leader, an example" },
    ],
    concept: "family",
    reflectionPrompt: "Who in your family needs your du'a more than your advice today?",
    practicalApplication: "Say it with their names in your heart. Then send them something kind.",
    defaultTarget: 10,
    secondsPerRepetition: 8,
    reviewStatus: "approved",
  },
  {
    id: "sleep_protection",
    title: "Protect me on that Day",
    arabic: "ٱللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak",
    translation: "O Allah, protect me from Your punishment on the Day You resurrect Your servants.",
    source: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3398", grade: "hasan sahih (Tirmidhi)", note: "Also Sunan Abi Dawud 5045." },
    occasions: ["before-sleep"],
    virtue: "The Prophet ﷺ placed his right hand under his cheek when he lay down and said these words. (Jami' at-Tirmidhi 3398)",
    explanation:
      "Sleep faces death, and death faces the Day. The Prophet ﷺ let the last thought of the night be the first thought of that Day, and asked for protection. It is a small sentence for the moment you are least defended.",
    vocabulary: [
      { arabic: "قِنِي", transliteration: "qini", meaning: "protect me", note: "root w-q-y, the root of taqwa" },
      { arabic: "تَبْعَثُ", transliteration: "tab'athu", meaning: "You resurrect" },
    ],
    concept: "akhirah",
    reflectionPrompt: "If tonight were the last, what would you want to have said?",
    practicalApplication: "Right hand under the cheek, then this, then sleep.",
    defaultTarget: 3,
    secondsPerRepetition: 5,
    reviewStatus: "approved",
  },
  {
    id: "rabbana_atina",
    title: "Rabbana atina",
    arabic: "رَبَّنَآ ءَاتِنَا فِى ٱلدُّنْيَا حَسَنَةً وَفِى ٱلْءَاخِرَةِ حَسَنَةً وَقِنَا عَذَابَ ٱلنَّارِ",
    transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar",
    translation: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
    source: { type: "quran", collection: "Qur'an", reference: "2:201" },
    virtueSource: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6389", grade: "sahih" },
    occasions: ["general", "provision", "gratitude"],
    virtue: "Anas said this was the supplication the Prophet ﷺ made most often. (Sahih al-Bukhari 6389)",
    explanation:
      "The du'a the Prophet ﷺ said most is astonishingly balanced. Good in this world: it is allowed to ask for that. Good in the next: it comes second, but it is the same word, hasanah. Then protection. Nothing extravagant, nothing ascetic. A whole life in one line.",
    vocabulary: [
      { arabic: "ءَاتِنَا", transliteration: "atina", meaning: "give us" },
      { arabic: "حَسَنَةً", transliteration: "hasanah", meaning: "good, something beautiful" },
      { arabic: "ٱلْءَاخِرَةِ", transliteration: "al-akhirah", meaning: "the Hereafter" },
    ],
    concept: "dua",
    reflectionPrompt: "What good in this world are you asking for, and would you still want it if it cost you the next?",
    practicalApplication: "Between the Yemeni corner and the Black Stone, and everywhere else.",
    defaultTarget: 33,
    secondsPerRepetition: 5,
    reviewStatus: "approved",
  },
  {
    id: "istighfar_extended",
    title: "Astaghfirullah al-'Azim",
    arabic: "أَسْتَغْفِرُ ٱللَّهَ ٱلَّذِي لَا إِلَٰهَ إِلَّا هُوَ ٱلْحَيُّ ٱلْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    transliteration: "Astaghfirullahal-ladhi la ilaha illa huwal-Hayyul-Qayyum wa atubu ilayh",
    translation: "I seek forgiveness of Allah, besides whom there is no god, the Ever-Living, the Sustainer, and I turn to Him in repentance.",
    source: { type: "hadith", collection: "Sunan Abi Dawud", reference: "1517", grade: "sahih (al-Hakim, al-Albani)", note: "Also Jami' at-Tirmidhi 3577." },
    occasions: ["forgiveness", "evening"],
    virtue: "Whoever says it, his sins are forgiven even if he had fled from the battlefield. (Sunan Abi Dawud 1517)",
    explanation:
      "Istighfar and tawbah are named side by side. Istighfar asks to be covered; tawbah means turning around. You can ask forgiveness without turning; this sentence refuses to. And it names Allah as Al-Hayy and Al-Qayyum, the same Names as Ayat al-Kursi: the One who is alive to hear you and steady enough to hold you while you change.",
    vocabulary: [
      { arabic: "أَتُوبُ", transliteration: "atubu", meaning: "I turn in repentance", note: "root t-w-b: to return" },
      { arabic: "إِلَيْهِ", transliteration: "ilayhi", meaning: "to Him" },
    ],
    concept: "tawbah",
    names: ["al-hayy", "al-qayyum", "at-tawwab"],
    reflectionPrompt: "What have you asked forgiveness for many times without ever turning from it?",
    practicalApplication: "Say it slowly, and with the last word, decide one small turn.",
    defaultTarget: 33,
    secondsPerRepetition: 5,
    reviewStatus: "approved",
  },
  {
    id: "dua_anxiety",
    title: "From worry and grief",
    arabic: "ٱللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ ٱلْهَمِّ وَٱلْحَزَنِ، وَٱلْعَجْزِ وَٱلْكَسَلِ، وَٱلْبُخْلِ وَٱلْجُبْنِ، وَضَلَعِ ٱلدَّيْنِ وَغَلَبَةِ ٱلرِّجَالِ",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dala'id-dayni wa ghalabatir-rijal",
    translation: "O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from miserliness and cowardice, from the burden of debt and from being overpowered by men.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6369", grade: "sahih" },
    occasions: ["difficulty", "morning", "evening"],
    virtue: "The Prophet ﷺ used to say this supplication often. (Sahih al-Bukhari 6369)",
    explanation:
      "Four pairs. Hamm is worry about what is coming; hazan is grief about what has passed. 'Ajz is being unable; kasal is being unwilling. Bukhl and jubn are the two ways we hold back what we have. Debt and domination are the two ways others hold us. The du'a names the whole geography of a heavy heart and asks for shelter from all of it.",
    vocabulary: [
      { arabic: "ٱلْهَمِّ", transliteration: "al-hamm", meaning: "worry (about the future)" },
      { arabic: "ٱلْحَزَنِ", transliteration: "al-hazan", meaning: "grief (about the past)" },
      { arabic: "ٱلْعَجْزِ", transliteration: "al-'ajz", meaning: "incapacity" },
      { arabic: "ٱلْكَسَلِ", transliteration: "al-kasal", meaning: "laziness" },
    ],
    concept: "protection",
    reflectionPrompt: "Which of the eight is closest to you today?",
    practicalApplication: "Say it in the morning before the inbox, and at night before the replay.",
    defaultTarget: 3,
    secondsPerRepetition: 14,
    reviewStatus: "approved",
  },
  {
    id: "salawat_ibrahimiyya",
    title: "Salawat Ibrahimiyyah",
    arabic:
      "ٱللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، ٱللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ",
    transliteration:
      "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad, kama sallayta 'ala Ibrahima wa 'ala ali Ibrahim, innaka Hamidun Majid. Allahumma barik 'ala Muhammadin wa 'ala ali Muhammad, kama barakta 'ala Ibrahima wa 'ala ali Ibrahim, innaka Hamidun Majid",
    translation:
      "O Allah, send blessings upon Muhammad and the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim; You are Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim; You are Praiseworthy, Glorious.",
    source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "3370", grade: "sahih" },
    occasions: ["general", "after-salah", "evening"],
    virtue: "When the Companions asked how to send blessings upon him, the Prophet ﷺ taught them these words. (Sahih al-Bukhari 3370)",
    explanation:
      "The salawat you already say in every prayer. Two requests: salah, that Allah praise and honour him, and barakah, that Allah make his goodness grow and remain. Each ends with two Names: Hamid, the One who is praised; Majid, the One whose glory is vast. You praise Allah as you ask Him to praise His Messenger.",
    vocabulary: [
      { arabic: "آلِ", transliteration: "ali", meaning: "the family of" },
      { arabic: "بَارِكْ", transliteration: "barik", meaning: "bless, make grow", note: "root b-r-k: barakah" },
      { arabic: "حَمِيدٌ", transliteration: "Hamid", meaning: "Praiseworthy" },
      { arabic: "مَجِيدٌ", transliteration: "Majid", meaning: "Glorious" },
    ],
    concept: "salawat",
    names: ["al-hamid", "al-majid"],
    reflectionPrompt: "You say this every day in prayer. When did you last hear it?",
    practicalApplication: "Read the meaning once today, then say it in your next prayer with the meaning present.",
    defaultTarget: 10,
    secondsPerRepetition: 15,
    reviewStatus: "approved",
  },
  {
    id: "afw_afiyah",
    title: "Pardon and wellbeing",
    arabic: "ٱللَّهُمَّ إِنِّي أَسْأَلُكَ ٱلْعَفْوَ وَٱلْعَافِيَةَ فِي ٱلدُّنْيَا وَٱلْآخِرَةِ",
    transliteration: "Allahumma inni as'alukal-'afwa wal-'afiyata fid-dunya wal-akhirah",
    translation: "O Allah, I ask You for pardon and wellbeing in this world and the next.",
    source: { type: "hadith", collection: "Sunan Abi Dawud", reference: "5074", grade: "sahih (al-Albani)", note: "Also Sunan Ibn Majah 3871. The full narration is longer; this is its opening." },
    occasions: ["morning", "evening", "protection"],
    virtue: "The Prophet ﷺ never left off saying these words in the morning and evening. (Sunan Abi Dawud 5074)",
    explanation:
      "'Afw is pardon that erases the trace, and 'afiyah is wellbeing in body, faith and affairs. The Prophet ﷺ said no one has been given anything better than 'afiyah after certainty. Two words that cover the inner and the outer life.",
    vocabulary: [
      { arabic: "ٱلْعَفْوَ", transliteration: "al-'afw", meaning: "pardon, erasure" },
      { arabic: "ٱلْعَافِيَةَ", transliteration: "al-'afiyah", meaning: "wellbeing, safety from harm" },
    ],
    concept: "dua",
    reflectionPrompt: "Where do you need pardon, and where do you need wellbeing?",
    practicalApplication: "Morning and evening. Say it for someone else too.",
    defaultTarget: 3,
    secondsPerRepetition: 7,
    reviewStatus: "approved",
  },
  {
    id: "asbahna",
    title: "Morning: Asbahna",
    arabic:
      "أَصْبَحْنَا وَأَصْبَحَ ٱلْمُلْكُ لِلَّهِ، وَٱلْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا ٱللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ ٱلْمُلْكُ وَلَهُ ٱلْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration:
      "Asbahna wa asbahal-mulku lillah, walhamdulillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir",
    translation:
      "We have entered the morning and the dominion has entered the morning belonging to Allah. All praise is for Allah. There is no god but Allah alone, without partner; His is the dominion and His is the praise, and He is able over all things.",
    source: { type: "hadith", collection: "Sahih Muslim", reference: "2723", grade: "sahih", note: "In the evening: Amsayna wa amsal-mulku lillah." },
    occasions: ["morning", "evening"],
    virtue: "The Prophet ﷺ said these words in the morning, and the evening form at night. (Sahih Muslim 2723)",
    explanation:
      "The morning did not just happen to you. It happened to the whole kingdom, and the kingdom is Allah's. The sentence widens the frame from your day to His dominion, and then places the full tahlil inside it. You wake up small, in something vast, and it is His.",
    vocabulary: [
      { arabic: "أَصْبَحْنَا", transliteration: "asbahna", meaning: "we have entered the morning" },
      { arabic: "ٱلْمُلْكُ", transliteration: "al-mulk", meaning: "the dominion" },
    ],
    concept: "tawhid",
    names: ["al-malik"],
    reflectionPrompt: "Whose kingdom did you wake up in this morning?",
    practicalApplication: "After Fajr, before the day's first task. In the evening, swap asbahna for amsayna.",
    defaultTarget: 3,
    secondsPerRepetition: 12,
    reviewStatus: "approved",
  },
  {
    id: "ikhlas",
    title: "Surah al-Ikhlas",
    arabic: "قُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ",
    transliteration: "Qul huwallahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakul-lahu kufuwan ahad",
    translation: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, and there is none comparable to Him.",
    source: { type: "quran", collection: "Qur'an", reference: "112:1–4" },
    virtueSource: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3575", grade: "hasan sahih (Tirmidhi)", note: "Also Sunan Abi Dawud 5082: al-Ikhlas, al-Falaq and an-Nas three times morning and evening suffice you against everything." },
    occasions: ["morning", "evening", "before-sleep", "protection"],
    virtue: "Recite al-Ikhlas, al-Falaq and an-Nas three times in the morning and evening, and they will suffice you against everything. (Jami' at-Tirmidhi 3575; Sunan Abi Dawud 5082)",
    explanation:
      "Four lines that describe Allah entirely by what He is and is not. Ahad: One, in a way nothing else is one. As-Samad: the One everything needs, who needs nothing. The surah is called Ikhlas, sincerity, because knowing Allah this way leaves the heart with no one else to turn to.",
    vocabulary: [
      { arabic: "أَحَدٌ", transliteration: "ahad", meaning: "One, unique" },
      { arabic: "ٱلصَّمَدُ", transliteration: "as-Samad", meaning: "the Eternal Refuge, the One all depend upon" },
      { arabic: "كُفُوًا", transliteration: "kufuwan", meaning: "equal, comparable" },
    ],
    concept: "tawhid",
    names: ["al-ahad", "as-samad"],
    reflectionPrompt: "What do you depend on that depends on something else?",
    practicalApplication: "Three times each of the three surahs, morning and evening. Blow lightly into cupped hands before sleep and wipe over the body, as the Prophet ﷺ did.",
    defaultTarget: 3,
    secondsPerRepetition: 10,
    reviewStatus: "approved",
  },
  {
    id: "ya_hayyu_ya_qayyum",
    title: "Ya Hayyu ya Qayyum",
    arabic: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ",
    transliteration: "Ya Hayyu ya Qayyum, birahmatika astaghith, aslih li sha'ni kullahu wa la takilni ila nafsi tarfata 'ayn",
    translation: "O Ever-Living, O Sustainer, by Your mercy I call for help. Set right all my affairs, and do not leave me to myself for the blink of an eye.",
    source: { type: "hadith", collection: "Al-Mustadrak of al-Hakim", reference: "1/545", grade: "hasan (al-Albani)", note: "Also in an-Nasa'i's 'Amal al-Yawm wal-Laylah. Grading should be confirmed by a reviewer." },
    occasions: ["difficulty", "morning", "evening"],
    virtue: "The Prophet ﷺ taught Fatimah to say these words in the morning and evening. (Al-Mustadrak 1/545)",
    explanation:
      "Two Names, then a cry for help, then the most honest request a person can make: do not leave me to myself, not even for a blink. Whoever has watched their own heart for a day knows why. The du'a admits that self-reliance is the real danger and that mercy is the only rescue.",
    vocabulary: [
      { arabic: "أَسْتَغِيثُ", transliteration: "astaghith", meaning: "I call for help, rescue" },
      { arabic: "أَصْلِحْ", transliteration: "aslih", meaning: "set right, make good" },
      { arabic: "تَكِلْنِي", transliteration: "takilni", meaning: "leave me, entrust me" },
      { arabic: "طَرْفَةَ عَيْنٍ", transliteration: "tarfata 'ayn", meaning: "the blink of an eye" },
    ],
    concept: "tawakkul",
    names: ["al-hayy", "al-qayyum"],
    reflectionPrompt: "When did you last rely on yourself and find out what that was worth?",
    practicalApplication: "Say it when you are about to make a decision that matters.",
    defaultTarget: 3,
    secondsPerRepetition: 10,
    reviewStatus: "review",
  },
];

export const ADHKAR_BY_ID: Record<string, DhikrItem> = Object.fromEntries(ADHKAR.map((d) => [d.id, d]));

export function getDhikr(id: string): DhikrItem {
  const item = ADHKAR_BY_ID[id];
  if (!item) throw new Error(`Unknown dhikr: ${id}`);
  return item;
}

/** Adhkar that are eligible for the free tasbih counter. */
export const FREE_TASBIH_IDS = [
  "subhanallah",
  "alhamdulillah",
  "allahu_akbar",
  "la_ilaha_illallah",
  "astaghfirullah",
  "salawat",
  "hawqala",
  "subhanallahi_wa_bihamdihi",
  "subhanallahi_wa_bihamdihi_azim",
  "tahlil_full",
  "hasbunallah",
  "dua_of_yunus",
  "istighfar_extended",
  "rabbana_atina",
] as const;
