import type { HadithItem } from "./types";

/** Paraphrased hadith with collection and number. The wording is a paraphrase; keep the reference with it. */
export const HADITHS: HadithItem[] = [
  { id: "h-consistency", title: "The most beloved deeds", text: "The most beloved deeds to Allah are those done most consistently, even if they are small.", source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6465", grade: "sahih", note: "Also Sahih Muslim 783." }, themes: ["consistency", "habit", "small acts"], reviewStatus: "approved" },
  { id: "h-living-dead", title: "The living and the dead", text: "The likeness of the one who remembers his Lord and the one who does not is the likeness of the living and the dead.", source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6407", grade: "sahih" }, themes: ["dhikr", "heart", "life"], reviewStatus: "approved" },
  { id: "h-with-him", title: "I am with him", text: "Allah says: I am as My servant thinks I am, and I am with him when he remembers Me.", source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "7405", grade: "sahih", note: "Also Sahih Muslim 2675." }, themes: ["dhikr", "closeness", "hope"], reviewStatus: "approved" },
  { id: "h-moist-tongue", title: "Keep your tongue moist", text: "A man said: the laws of Islam are many for me; tell me something I can hold on to. The Prophet ﷺ said: Let your tongue remain moist with the remembrance of Allah.", source: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3375", grade: "hasan gharib (Tirmidhi)" }, themes: ["dhikr", "simplicity", "habit"], reviewStatus: "approved" },
  { id: "h-gatherings", title: "Gatherings of remembrance", text: "No people sit remembering Allah except that the angels surround them, mercy covers them, tranquillity descends upon them, and Allah mentions them to those who are with Him.", source: { type: "hadith", collection: "Sahih Muslim", reference: "2700", grade: "sahih" }, themes: ["together", "dhikr", "tranquillity", "circles"], reviewStatus: "approved" },
  { id: "h-return", title: "Return often", text: "The Prophet ﷺ said that he seeks Allah's forgiveness and turns to Him in repentance more than seventy times each day.", source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6307", grade: "sahih" }, themes: ["repentance", "istighfar"], reviewStatus: "approved" },
  { id: "h-light", title: "Light on the tongue", text: "Two words are light on the tongue, heavy on the scale, and beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-'Azim.", source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6682", grade: "sahih", note: "Also Sahih Muslim 2694." }, themes: ["glorification", "tasbih"], reviewStatus: "approved" },
  { id: "h-praise", title: "Praise fills the scale", text: "Purity is half of faith, and Alhamdulillah fills the scale.", source: { type: "hadith", collection: "Sahih Muslim", reference: "223", grade: "sahih" }, themes: ["gratitude", "hamd"], reviewStatus: "approved" },
  { id: "h-salawat", title: "Send one blessing", text: "Whoever sends one blessing upon the Prophet ﷺ, Allah sends ten blessings upon him.", source: { type: "hadith", collection: "Sahih Muslim", reference: "408", grade: "sahih" }, themes: ["salawat", "prophet"], reviewStatus: "approved" },
  { id: "h-treasure", title: "A treasure from Paradise", text: "The Prophet ﷺ described La hawla wa la quwwata illa billah as a treasure from the treasures of Paradise.", source: { type: "hadith", collection: "Sahih al-Bukhari", reference: "6409", grade: "sahih", note: "Also Sahih Muslim 2704." }, themes: ["reliance", "tawakkul"], reviewStatus: "approved" },
  { id: "h-afiyah", title: "Nothing better than wellbeing", text: "Ask Allah for pardon and wellbeing, for after certainty no one has been given anything better than wellbeing.", source: { type: "hadith", collection: "Jami' at-Tirmidhi", reference: "3558", grade: "hasan (Tirmidhi)", note: "Grading should be confirmed by a reviewer." }, themes: ["afiyah", "dua"], reviewStatus: "review" },
];

export const HADITH_BY_ID: Record<string, HadithItem> = Object.fromEntries(HADITHS.map((h) => [h.id, h]));
