import type { NameOfAllah } from "./types";

/** Names of Allah referenced by adhkar in the library, each with a Qur'anic reference. */
export const NAMES_OF_ALLAH: NameOfAllah[] = [
  { id: "ar-rahman", arabic: "ٱلرَّحْمَٰنُ", transliteration: "Ar-Rahman", meaning: "The Most Merciful, whose mercy encompasses everything", source: { type: "quran", collection: "Qur'an", reference: "55:1" }, reflection: "His mercy reached you before you asked for it.", reviewStatus: "approved" },
  { id: "ar-rabb", arabic: "ٱلرَّبُّ", transliteration: "Ar-Rabb", meaning: "The Lord: the One who owns, nurtures and sustains", source: { type: "quran", collection: "Qur'an", reference: "1:2" }, reflection: "Rabb al-'alamin: not only your Lord, but the Lord of every world you will never see.", reviewStatus: "approved" },
  { id: "as-salam", arabic: "ٱلسَّلَامُ", transliteration: "As-Salam", meaning: "The Source of Peace, free of every defect", source: { type: "quran", collection: "Qur'an", reference: "59:23" }, reflection: "Peace is not a state you produce. It is a Name you turn toward.", reviewStatus: "approved" },
  { id: "al-quddus", arabic: "ٱلْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy, utterly pure", source: { type: "quran", collection: "Qur'an", reference: "59:23" }, reflection: "Tasbih is the tongue's way of saying this Name.", reviewStatus: "approved" },
  { id: "al-malik", arabic: "ٱلْمَلِكُ", transliteration: "Al-Malik", meaning: "The King, the Owner of all dominion", source: { type: "quran", collection: "Qur'an", reference: "59:23" }, reflection: "Lahul-mulk: whatever you are fighting over, He owns.", reviewStatus: "approved" },
  { id: "al-ghafur", arabic: "ٱلْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The All-Forgiving, who covers sins completely", source: { type: "quran", collection: "Qur'an", reference: "39:53" }, reflection: "The verse that forbids despair ends with this Name.", reviewStatus: "approved" },
  { id: "at-tawwab", arabic: "ٱلتَّوَّابُ", transliteration: "At-Tawwab", meaning: "The One who constantly accepts repentance", source: { type: "quran", collection: "Qur'an", reference: "2:37" }, reflection: "He turned to Adam before Adam knew how to turn to Him.", reviewStatus: "approved" },
  { id: "al-wakil", arabic: "ٱلْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee, the Disposer of affairs", source: { type: "quran", collection: "Qur'an", reference: "3:173" }, reflection: "You can hand Him the outcome. He does not drop things.", reviewStatus: "approved" },
  { id: "al-azim", arabic: "ٱلْعَظِيمُ", transliteration: "Al-'Azim", meaning: "The Magnificent, the Supreme in greatness", source: { type: "quran", collection: "Qur'an", reference: "2:255" }, reflection: "Ayat al-Kursi ends with this Name.", reviewStatus: "approved" },
  { id: "al-kabir", arabic: "ٱلْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Incomparably Great", source: { type: "quran", collection: "Qur'an", reference: "13:9" }, reflection: "Allahu Akbar is this Name in motion.", reviewStatus: "approved" },
  { id: "al-hayy", arabic: "ٱلْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living", source: { type: "quran", collection: "Qur'an", reference: "2:255" }, reflection: "Everything alive borrows its life. His is His own.", reviewStatus: "approved" },
  { id: "al-qayyum", arabic: "ٱلْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Sustaining, by whom all things stand", source: { type: "quran", collection: "Qur'an", reference: "2:255" }, reflection: "Neither drowsiness nor sleep. He is holding it while you rest.", reviewStatus: "approved" },
  { id: "al-halim", arabic: "ٱلْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing, who does not hasten to punish", source: { type: "quran", collection: "Qur'an", reference: "2:235" }, reflection: "The space between your mistake and its consequence is His hilm.", reviewStatus: "approved" },
  { id: "al-latif", arabic: "ٱللَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle and Kind, who reaches you gently", source: { type: "quran", collection: "Qur'an", reference: "42:19" }, reflection: "Some of His kindness is too fine to notice until years later.", reviewStatus: "approved" },
  { id: "ar-razzaq", arabic: "ٱلرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider, who provides again and again", source: { type: "quran", collection: "Qur'an", reference: "51:58" }, reflection: "The intensive form: not a provider, but the One who never stops providing.", reviewStatus: "approved" },
  { id: "ash-shakur", arabic: "ٱلشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Appreciative, who rewards small deeds greatly", source: { type: "quran", collection: "Qur'an", reference: "35:30" }, reflection: "He is grateful for your thirty-three. He multiplies it.", reviewStatus: "approved" },
  { id: "al-karim", arabic: "ٱلْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous, the Noble", source: { type: "quran", collection: "Qur'an", reference: "82:6" }, reflection: "The verse asks: what deceived you about your Generous Lord?", reviewStatus: "approved" },
  { id: "al-hamid", arabic: "ٱلْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy, deserving of all praise", source: { type: "quran", collection: "Qur'an", reference: "31:26" }, reflection: "Alhamdulillah is true whether or not anyone says it.", reviewStatus: "approved" },
  { id: "al-majid", arabic: "ٱلْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Glorious, vast in honour", source: { type: "quran", collection: "Qur'an", reference: "11:73" }, reflection: "You say it in every prayer: innaka Hamidun Majid.", reviewStatus: "approved" },
  { id: "as-sami", arabic: "ٱلسَّمِيعُ", transliteration: "As-Sami'", meaning: "The All-Hearing", source: { type: "quran", collection: "Qur'an", reference: "2:127" }, reflection: "The whisper counts.", reviewStatus: "approved" },
  { id: "al-alim", arabic: "ٱلْعَلِيمُ", transliteration: "Al-'Alim", meaning: "The All-Knowing", source: { type: "quran", collection: "Qur'an", reference: "2:127" }, reflection: "You do not need to explain yourself to Him. You only need to turn.", reviewStatus: "approved" },
  { id: "al-qadir", arabic: "ٱلْقَدِيرُ", transliteration: "Al-Qadir", meaning: "The All-Able, whose power reaches everything", source: { type: "quran", collection: "Qur'an", reference: "2:20" }, reflection: "'Ala kulli shay'in qadir. Including the thing you decided was impossible.", reviewStatus: "approved" },
  { id: "al-wadud", arabic: "ٱلْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving, the Most Affectionate", source: { type: "quran", collection: "Qur'an", reference: "85:14" }, reflection: "Named beside Al-Ghafur: He forgives, and He loves.", reviewStatus: "approved" },
  { id: "al-ahad", arabic: "ٱلْأَحَدُ", transliteration: "Al-Ahad", meaning: "The One, unique in every way", source: { type: "quran", collection: "Qur'an", reference: "112:1" }, reflection: "Not one among many. One in a way nothing else can be.", reviewStatus: "approved" },
  { id: "as-samad", arabic: "ٱلصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal Refuge, needed by all and needing none", source: { type: "quran", collection: "Qur'an", reference: "112:2" }, reflection: "Everything leans on something. Everything, eventually, leans on Him.", reviewStatus: "approved" },
];

export const NAMES_BY_ID: Record<string, NameOfAllah> = Object.fromEntries(NAMES_OF_ALLAH.map((n) => [n.id, n]));
